var fretArt = {
  frets: [],
  notes: [],
  shapes: [],
  strings: [],
  stringPos: [],
  shadowFrets: [],
  fretsIsShowing: false,
  stringsIsShowing: false,
  foundScale: [],
  foundScaleIds: [],
  filteredScaleIds: [],
  numberOfShapes: 23,
  arrPositionList: null,
  modes: null,
  linesVisible: false,
  invisible: false,
  cPedalPlay: false,
  noteNameList: ["E","F","Gb","G","Ab","A","Bb","B","C","Db","D","Eb"],
  initialStringIndices: null,
  currentKey: null,
  currentKeyName: null,
  currentMode: null,

  selectedModeNameHolder: null,
  scaleIndex: 0,
  scaleCounter: 0,
  selectedKeyNameHolder: null,
  keyIndex: 8,
  keyCounter: 8
}
