/*
6.7 p5.js clicking on objects
Code for video https://vimeo.com/channels/learningp5js/141919520
*/

var frets = [];


function setup() {

  createCanvas(700, 500);
  for (var guitar = 0; guitar < 3; guitar++) {

    var guitarSpacing = 120;
    var guitarGroupLeftMargin = 110;
    var guitarGroupTopMargin = 70;
    var fretWidth = 20;

    var guitarCounter = guitar * guitarSpacing;
    // sets to 6 strings
    for (var guitStr = 0; guitStr < 6; guitStr++){
      // sets to 24 frets
      for (var i = 0; i < 25; i++) {

        var x = guitarGroupLeftMargin + (i * fretWidth);
        var y = guitarGroupTopMargin + (guitStr * 10) + (guitarCounter + 30);
        frets.push(new Fret(x, y, frets.length));
      }
    }
  }
}

function play(){

}

function mousePressed() {
  for (var i = 0; i < frets.length; i++) {
    frets[i].clicked();
  }
}

function draw() {
  background(0);
  for (var i = 0; i < frets.length; i++) {
    frets[i].display();
  }
}

var g1 = 0;
var g2 = 150;
var g3 = 300;

var str1 = 0;
var str2 = 25;
var str3 = 50;
var str4 = 75;
var str5 = 100;
var str6 = 125;

var buttonHandlers = {
  clearButton: function() {
    for (i = 0; i < frets.length; i++) {
      frets[i].active = false;
    }
  },
  
  ionianButton: function() {
    for (i = 0; i < frets.length; i++) {
      frets[i].active = false;
    }
    // string 1
    frets[0 + g1 + str1].active = true; frets[1 + g1 + str1].active = true; frets[3 + g1 + str1].active = true; frets[5 + g1 + str1].active = true; frets[7 + g1 + str1].active = true; frets[8 + g1 + str1].active = true; frets[10 + g1 + str1].active = true; frets[12 + g1 + str1].active = true; frets[13 + g1 + str1].active = true; frets[15 + g1 + str1].active = true; frets[17 + g1 + str1].active = true; frets[19 + g1 + str1].active = true; frets[20 + g1 + str1].active = true; frets[22 + g1 + str1].active = true; frets[24 + g1 + str1].active = true;
    frets[0 + g2 + str1].active = true; frets[1 + g2 + str1].active = true; frets[3 + g2 + str1].active = true; frets[5 + g2 + str1].active = true; frets[7 + g2 + str1].active = true; frets[8 + g2 + str1].active = true; frets[10 + g2 + str1].active = true; frets[12 + g2 + str1].active = true; frets[13 + g2 + str1].active = true; frets[15 + g2 + str1].active = true; frets[17 + g2 + str1].active = true; frets[19 + g2 + str1].active = true; frets[20 + g2 + str1].active = true; frets[22 + g2 + str1].active = true; frets[24 + g2 + str1].active = true;
    frets[0 + g3 + str1].active = true; frets[1 + g3 + str1].active = true; frets[3 + g3 + str1].active = true; frets[5 + g3 + str1].active = true; frets[7 + g3 + str1].active = true; frets[8 + g3 + str1].active = true; frets[10 + g3 + str1].active = true; frets[12 + g3 + str1].active = true; frets[13 + g3 + str1].active = true; frets[15 + g3 + str1].active = true; frets[17 + g3 + str1].active = true; frets[19 + g3 + str1].active = true; frets[20 + g3 + str1].active = true; frets[22 + g3 + str1].active = true; frets[24 + g3 + str1].active = true;
    // string 2
    frets[0 + g1 + str2].active = true; frets[1 + g1 + str2].active = true; frets[3 + g1 + str2].active = true; frets[5 + g1 + str2].active = true; frets[6 + g1 + str2].active = true; frets[8 + g1 + str2].active = true; frets[10 + g1 + str2].active = true; frets[12 + g1 + str2].active = true; frets[13 + g1 + str2].active = true; frets[15 + g1 + str2].active = true; frets[17 + g1 + str2].active = true; frets[18 + g1 + str2].active = true; frets[20 + g1 + str2].active = true; frets[22 + g1 + str2].active = true; frets[24 + g1 + str2].active = true;
    frets[0 + g2 + str2].active = true; frets[1 + g2 + str2].active = true; frets[3 + g2 + str2].active = true; frets[5 + g2 + str2].active = true; frets[6 + g2 + str2].active = true; frets[8 + g2 + str2].active = true; frets[10 + g2 + str2].active = true; frets[12 + g2 + str2].active = true; frets[13 + g2 + str2].active = true; frets[15 + g2 + str2].active = true; frets[17 + g2 + str2].active = true; frets[18 + g2 + str2].active = true; frets[20 + g2 + str2].active = true; frets[22 + g2 + str2].active = true; frets[24 + g2 + str2].active = true;
    frets[0 + g3 + str2].active = true; frets[1 + g3 + str2].active = true; frets[3 + g3 + str2].active = true; frets[5 + g3 + str2].active = true; frets[6 + g3 + str2].active = true; frets[8 + g3 + str2].active = true; frets[10 + g3 + str2].active = true; frets[12 + g3 + str2].active = true; frets[13 + g3 + str2].active = true; frets[15 + g3 + str2].active = true; frets[17 + g3 + str2].active = true; frets[18 + g3 + str2].active = true; frets[20 + g3 + str2].active = true; frets[22 + g3 + str2].active = true; frets[24 + g3 + str2].active = true;
    // string 3
    frets[0 + g1 + str3].active = true; frets[2 + g1 + str3].active = true; frets[4 + g1 + str3].active = true; frets[5 + g1 + str3].active = true; frets[7 + g1 + str3].active = true; frets[9 + g1 + str3].active = true; frets[10 + g1 + str3].active = true; frets[12 + g1 + str3].active = true; frets[14 + g1 + str3].active = true; frets[16 + g1 + str3].active = true; frets[17 + g1 + str3].active = true; frets[19 + g1 + str3].active = true; frets[21 + g1 + str3].active = true; frets[22 + g1 + str3].active = true; frets[24 + g1 + str3].active = true;
    frets[0 + g2 + str3].active = true; frets[2 + g2 + str3].active = true; frets[4 + g2 + str3].active = true; frets[5 + g2 + str3].active = true; frets[7 + g2 + str3].active = true; frets[9 + g2 + str3].active = true; frets[10 + g2 + str3].active = true; frets[12 + g2 + str3].active = true; frets[14 + g2 + str3].active = true; frets[16 + g2 + str3].active = true; frets[17 + g2 + str3].active = true; frets[19 + g2 + str3].active = true; frets[21 + g2 + str3].active = true; frets[22 + g2 + str3].active = true; frets[24 + g2 + str3].active = true;
    frets[0 + g3 + str3].active = true; frets[2 + g3 + str3].active = true; frets[4 + g3 + str3].active = true; frets[5 + g3 + str3].active = true; frets[7 + g3 + str3].active = true; frets[9 + g3 + str3].active = true; frets[10 + g3 + str3].active = true; frets[12 + g3 + str3].active = true; frets[14 + g3 + str3].active = true; frets[16 + g3 + str3].active = true; frets[17 + g3 + str3].active = true; frets[19 + g3 + str3].active = true; frets[21 + g3 + str3].active = true; frets[22 + g3 + str3].active = true; frets[24 + g3 + str3].active = true;
    // string 4
    frets[0 + g1 + str4].active = true; frets[2 + g1 + str4].active = true; frets[3 + g1 + str4].active = true; frets[5 + g1 + str4].active = true; frets[7 + g1 + str4].active = true; frets[9 + g1 + str4].active = true; frets[10 + g1 + str4].active = true; frets[12 + g1 + str4].active = true; frets[14 + g1 + str4].active = true; frets[15 + g1 + str4].active = true; frets[17 + g1 + str4].active = true; frets[19 + g1 + str4].active = true; frets[21 + g1 + str4].active = true; frets[22 + g1 + str4].active = true; frets[24 + g1 + str4].active = true;
    frets[0 + g2 + str4].active = true; frets[2 + g2 + str4].active = true; frets[3 + g2 + str4].active = true; frets[5 + g2 + str4].active = true; frets[7 + g2 + str4].active = true; frets[9 + g2 + str4].active = true; frets[10 + g2 + str4].active = true; frets[12 + g2 + str4].active = true; frets[14 + g2 + str4].active = true; frets[15 + g2 + str4].active = true; frets[17 + g2 + str4].active = true; frets[19 + g2 + str4].active = true; frets[21 + g2 + str4].active = true; frets[22 + g2 + str4].active = true; frets[24 + g2 + str4].active = true;
    frets[0 + g3 + str4].active = true; frets[2 + g3 + str4].active = true; frets[3 + g3 + str4].active = true; frets[5 + g3 + str4].active = true; frets[7 + g3 + str4].active = true; frets[9 + g3 + str4].active = true; frets[10 + g3 + str4].active = true; frets[12 + g3 + str4].active = true; frets[14 + g3 + str4].active = true; frets[15 + g3 + str4].active = true; frets[17 + g3 + str4].active = true; frets[19 + g3 + str4].active = true; frets[21 + g3 + str4].active = true; frets[22 + g3 + str4].active = true; frets[24 + g3 + str4].active = true;
    // string 5
    frets[0 + g1 + str5].active = true; frets[2 + g1 + str5].active = true; frets[3 + g1 + str5].active = true; frets[5 + g1 + str5].active = true; frets[7 + g1 + str5].active = true; frets[8 + g1 + str5].active = true; frets[10 + g1 + str5].active = true; frets[12 + g1 + str5].active = true; frets[14 + g1 + str5].active = true; frets[15 + g1 + str5].active = true; frets[17 + g1 + str5].active = true; frets[19 + g1 + str5].active = true; frets[20 + g1 + str5].active = true; frets[22 + g1 + str5].active = true; frets[24 + g1 + str5].active = true;
    frets[0 + g2 + str5].active = true; frets[2 + g2 + str5].active = true; frets[3 + g2 + str5].active = true; frets[5 + g2 + str5].active = true; frets[7 + g2 + str5].active = true; frets[8 + g2 + str5].active = true; frets[10 + g2 + str5].active = true; frets[12 + g2 + str5].active = true; frets[14 + g2 + str5].active = true; frets[15 + g2 + str5].active = true; frets[17 + g2 + str5].active = true; frets[19 + g2 + str5].active = true; frets[20 + g2 + str5].active = true; frets[22 + g2 + str5].active = true; frets[24 + g2 + str5].active = true;
    frets[0 + g3 + str5].active = true; frets[2 + g3 + str5].active = true; frets[3 + g3 + str5].active = true; frets[5 + g3 + str5].active = true; frets[7 + g3 + str5].active = true; frets[8 + g3 + str5].active = true; frets[10 + g3 + str5].active = true; frets[12 + g3 + str5].active = true; frets[14 + g3 + str5].active = true; frets[15 + g3 + str5].active = true; frets[17 + g3 + str5].active = true; frets[19 + g3 + str5].active = true; frets[20 + g3 + str5].active = true; frets[22 + g3 + str5].active = true; frets[24 + g3 + str5].active = true;
    // string 6
    frets[0 + g1 + str6].active = true; frets[1 + g1 + str6].active = true; frets[3 + g1 + str6].active = true; frets[5 + g1 + str6].active = true; frets[7 + g1 + str6].active = true; frets[8 + g1 + str6].active = true; frets[10 + g1 + str6].active = true; frets[12 + g1 + str6].active = true; frets[13 + g1 + str6].active = true; frets[15 + g1 + str6].active = true; frets[17 + g1 + str6].active = true; frets[19 + g1 + str6].active = true; frets[20 + g1 + str6].active = true; frets[22 + g1 + str6].active = true; frets[24 + g1 + str6].active = true;
    frets[0 + g2 + str6].active = true; frets[1 + g2 + str6].active = true; frets[3 + g2 + str6].active = true; frets[5 + g2 + str6].active = true; frets[7 + g2 + str6].active = true; frets[8 + g2 + str6].active = true; frets[10 + g2 + str6].active = true; frets[12 + g2 + str6].active = true; frets[13 + g2 + str6].active = true; frets[15 + g2 + str6].active = true; frets[17 + g2 + str6].active = true; frets[19 + g2 + str6].active = true; frets[20 + g2 + str6].active = true; frets[22 + g2 + str6].active = true; frets[24 + g2 + str6].active = true;
    frets[0 + g3 + str6].active = true; frets[1 + g3 + str6].active = true; frets[3 + g3 + str6].active = true; frets[5 + g3 + str6].active = true; frets[7 + g3 + str6].active = true; frets[8 + g3 + str6].active = true; frets[10 + g3 + str6].active = true; frets[12 + g3 + str6].active = true; frets[13 + g3 + str6].active = true; frets[15 + g3 + str6].active = true; frets[17 + g3 + str6].active = true; frets[19 + g3 + str6].active = true; frets[20 + g3 + str6].active = true; frets[22 + g3 + str6].active = true; frets[24 + g3 + str6].active = true;
  },

  dorianButton: function() {
    for (i = 0; i < frets.length; i++) {
      frets[i].active = false;
    }
    // string 1
    frets[0 + g1 + str1].active = false; frets[1 + g1 + str1].active = true; frets[3 + g1 + str1].active = true; frets[5 + g1 + str1].active = true; frets[6 + g1 + str1].active = true; frets[8 + g1 + str1].active = true; frets[10 + g1 + str1].active = true; frets[11 + g1 + str1].active = true; frets[13 + g1 + str1].active = true; frets[15 + g1 + str1].active = true; frets[17 + g1 + str1].active = true; frets[18 + g1 + str1].active = true; frets[20 + g1 + str1].active = true; frets[22 + g1 + str1].active = true; frets[23 + g1 + str1].active = true;
    frets[0 + g2 + str1].active = false; frets[1 + g2 + str1].active = true; frets[3 + g2 + str1].active = true; frets[5 + g2 + str1].active = true; frets[6 + g2 + str1].active = true; frets[8 + g2 + str1].active = true; frets[10 + g2 + str1].active = true; frets[11 + g2 + str1].active = true; frets[13 + g2 + str1].active = true; frets[15 + g2 + str1].active = true; frets[17 + g2 + str1].active = true; frets[18 + g2 + str1].active = true; frets[20 + g2 + str1].active = true; frets[22 + g2 + str1].active = true; frets[23 + g2 + str1].active = true;
    frets[0 + g3 + str1].active = false; frets[1 + g3 + str1].active = true; frets[3 + g3 + str1].active = true; frets[5 + g3 + str1].active = true; frets[6 + g3 + str1].active = true; frets[8 + g3 + str1].active = true; frets[10 + g3 + str1].active = true; frets[11 + g3 + str1].active = true; frets[13 + g3 + str1].active = true; frets[15 + g3 + str1].active = true; frets[17 + g3 + str1].active = true; frets[18 + g3 + str1].active = true; frets[20 + g3 + str1].active = true; frets[22 + g3 + str1].active = true; frets[23 + g3 + str1].active = true;
    // string 2
    frets[0 + g1 + str2].active = false; frets[1 + g1 + str2].active = true; frets[3 + g1 + str2].active = true; frets[4 + g1 + str2].active = true; frets[6 + g1 + str2].active = true; frets[8 + g1 + str2].active = true; frets[10 + g1 + str2].active = true; frets[11 + g1 + str2].active = true; frets[13 + g1 + str2].active = true; frets[15 + g1 + str2].active = true; frets[16 + g1 + str2].active = true; frets[18 + g1 + str2].active = true; frets[20 + g1 + str2].active = true; frets[22 + g1 + str2].active = true; frets[23 + g1 + str2].active = true;
    frets[0 + g2 + str2].active = false; frets[1 + g2 + str2].active = true; frets[3 + g2 + str2].active = true; frets[4 + g2 + str2].active = true; frets[6 + g2 + str2].active = true; frets[8 + g2 + str2].active = true; frets[10 + g2 + str2].active = true; frets[11 + g2 + str2].active = true; frets[13 + g2 + str2].active = true; frets[15 + g2 + str2].active = true; frets[16 + g2 + str2].active = true; frets[18 + g2 + str2].active = true; frets[20 + g2 + str2].active = true; frets[22 + g2 + str2].active = true; frets[23 + g2 + str2].active = true;
    frets[0 + g3 + str2].active = false; frets[1 + g3 + str2].active = true; frets[3 + g3 + str2].active = true; frets[4 + g3 + str2].active = true; frets[6 + g3 + str2].active = true; frets[8 + g3 + str2].active = true; frets[10 + g3 + str2].active = true; frets[11 + g3 + str2].active = true; frets[13 + g3 + str2].active = true; frets[15 + g3 + str2].active = true; frets[16 + g3 + str2].active = true; frets[18 + g3 + str2].active = true; frets[20 + g3 + str2].active = true; frets[22 + g3 + str2].active = true; frets[23 + g3 + str2].active = true;
    // string 3
    frets[0 + g1 + str3].active = true; frets[2 + g1 + str3].active = true; frets[3 + g1 + str3].active = true; frets[5 + g1 + str3].active = true; frets[7 + g1 + str3].active = true; frets[8 + g1 + str3].active = true; frets[10 + g1 + str3].active = true; frets[12 + g1 + str3].active = true; frets[14 + g1 + str3].active = true; frets[15 + g1 + str3].active = true; frets[17 + g1 + str3].active = true; frets[19 + g1 + str3].active = true; frets[20 + g1 + str3].active = true; frets[22 + g1 + str3].active = true; frets[24 + g1 + str3].active = true;
    frets[0 + g2 + str3].active = true; frets[2 + g2 + str3].active = true; frets[3 + g2 + str3].active = true; frets[5 + g2 + str3].active = true; frets[7 + g2 + str3].active = true; frets[8 + g2 + str3].active = true; frets[10 + g2 + str3].active = true; frets[12 + g2 + str3].active = true; frets[14 + g2 + str3].active = true; frets[15 + g2 + str3].active = true; frets[17 + g2 + str3].active = true; frets[19 + g2 + str3].active = true; frets[20 + g2 + str3].active = true; frets[22 + g2 + str3].active = true; frets[24 + g2 + str3].active = true;
    frets[0 + g3 + str3].active = true; frets[2 + g3 + str3].active = true; frets[3 + g3 + str3].active = true; frets[5 + g3 + str3].active = true; frets[7 + g3 + str3].active = true; frets[8 + g3 + str3].active = true; frets[10 + g3 + str3].active = true; frets[12 + g3 + str3].active = true; frets[14 + g3 + str3].active = true; frets[15 + g3 + str3].active = true; frets[17 + g3 + str3].active = true; frets[19 + g3 + str3].active = true; frets[20 + g3 + str3].active = true; frets[22 + g3 + str3].active = true; frets[24 + g3 + str3].active = true;
    // string 4
    frets[0 + g1 + str4].active = true; frets[1 + g1 + str4].active = true; frets[3 + g1 + str4].active = true; frets[5 + g1 + str4].active = true; frets[7 + g1 + str4].active = true; frets[8 + g1 + str4].active = true; frets[10 + g1 + str4].active = true; frets[12 + g1 + str4].active = true; frets[13 + g1 + str4].active = true; frets[15 + g1 + str4].active = true; frets[17 + g1 + str4].active = true; frets[19 + g1 + str4].active = true; frets[20 + g1 + str4].active = true; frets[22 + g1 + str4].active = true; frets[24 + g1 + str4].active = true;
    frets[0 + g2 + str4].active = true; frets[1 + g2 + str4].active = true; frets[3 + g2 + str4].active = true; frets[5 + g2 + str4].active = true; frets[7 + g2 + str4].active = true; frets[8 + g2 + str4].active = true; frets[10 + g2 + str4].active = true; frets[12 + g2 + str4].active = true; frets[13 + g2 + str4].active = true; frets[15 + g2 + str4].active = true; frets[17 + g2 + str4].active = true; frets[19 + g2 + str4].active = true; frets[20 + g2 + str4].active = true; frets[22 + g2 + str4].active = true; frets[24 + g2 + str4].active = true;
    frets[0 + g3 + str4].active = true; frets[1 + g3 + str4].active = true; frets[3 + g3 + str4].active = true; frets[5 + g3 + str4].active = true; frets[7 + g3 + str4].active = true; frets[8 + g3 + str4].active = true; frets[10 + g3 + str4].active = true; frets[12 + g3 + str4].active = true; frets[13 + g3 + str4].active = true; frets[15 + g3 + str4].active = true; frets[17 + g3 + str4].active = true; frets[19 + g3 + str4].active = true; frets[20 + g3 + str4].active = true; frets[22 + g3 + str4].active = true; frets[24 + g3 + str4].active = true;
    // string 5
    frets[0 + g1 + str5].active = true; frets[1 + g1 + str5].active = true; frets[3 + g1 + str5].active = true; frets[5 + g1 + str5].active = true; frets[6 + g1 + str5].active = true; frets[8 + g1 + str5].active = true; frets[10 + g1 + str5].active = true; frets[12 + g1 + str5].active = true; frets[13 + g1 + str5].active = true; frets[15 + g1 + str5].active = true; frets[17 + g1 + str5].active = true; frets[18 + g1 + str5].active = true; frets[20 + g1 + str5].active = true; frets[22 + g1 + str5].active = true; frets[24 + g1 + str5].active = true;
    frets[0 + g2 + str5].active = true; frets[1 + g2 + str5].active = true; frets[3 + g2 + str5].active = true; frets[5 + g2 + str5].active = true; frets[6 + g2 + str5].active = true; frets[8 + g2 + str5].active = true; frets[10 + g2 + str5].active = true; frets[12 + g2 + str5].active = true; frets[13 + g2 + str5].active = true; frets[15 + g2 + str5].active = true; frets[17 + g2 + str5].active = true; frets[18 + g2 + str5].active = true; frets[20 + g2 + str5].active = true; frets[22 + g2 + str5].active = true; frets[24 + g2 + str5].active = true;
    frets[0 + g3 + str5].active = true; frets[1 + g3 + str5].active = true; frets[3 + g3 + str5].active = true; frets[5 + g3 + str5].active = true; frets[6 + g3 + str5].active = true; frets[8 + g3 + str5].active = true; frets[10 + g3 + str5].active = true; frets[12 + g3 + str5].active = true; frets[13 + g3 + str5].active = true; frets[15 + g3 + str5].active = true; frets[17 + g3 + str5].active = true; frets[18 + g3 + str5].active = true; frets[20 + g3 + str5].active = true; frets[22 + g3 + str5].active = true; frets[24 + g3 + str5].active = true;
    // string 6
    frets[0 + g1 + str6].active = false; frets[1 + g1 + str6].active = true; frets[3 + g1 + str6].active = true; frets[5 + g1 + str6].active = true; frets[6 + g1 + str6].active = true; frets[8 + g1 + str6].active = true; frets[10 + g1 + str6].active = true; frets[11 + g1 + str6].active = true; frets[13 + g1 + str6].active = true; frets[15 + g1 + str6].active = true; frets[17 + g1 + str6].active = true; frets[18 + g1 + str6].active = true; frets[20 + g1 + str6].active = true; frets[22 + g1 + str6].active = true; frets[23 + g1 + str6].active = true;
    frets[0 + g2 + str6].active = false; frets[1 + g2 + str6].active = true; frets[3 + g2 + str6].active = true; frets[5 + g2 + str6].active = true; frets[6 + g2 + str6].active = true; frets[8 + g2 + str6].active = true; frets[10 + g2 + str6].active = true; frets[11 + g2 + str6].active = true; frets[13 + g2 + str6].active = true; frets[15 + g2 + str6].active = true; frets[17 + g2 + str6].active = true; frets[18 + g2 + str6].active = true; frets[20 + g2 + str6].active = true; frets[22 + g2 + str6].active = true; frets[23 + g2 + str6].active = true;
    frets[0 + g3 + str6].active = false; frets[1 + g3 + str6].active = true; frets[3 + g3 + str6].active = true; frets[5 + g3 + str6].active = true; frets[6 + g3 + str6].active = true; frets[8 + g3 + str6].active = true; frets[10 + g3 + str6].active = true; frets[11 + g3 + str6].active = true; frets[13 + g3 + str6].active = true; frets[15 + g3 + str6].active = true; frets[17 + g3 + str6].active = true; frets[18 + g3 + str6].active = true; frets[20 + g3 + str6].active = true; frets[22 + g3 + str6].active = true; frets[23 + g3 + str6].active = true;
  },

  phrygianButton: function() {
    for (i = 0; i < frets.length; i++) {
      frets[i].active = false;
    }
    // string 1
    frets[0 + g1 + str1].active = false; frets[1 + g1 + str1].active = true; frets[3 + g1 + str1].active = true; frets[4 + g1 + str1].active = true; frets[6 + g1 + str1].active = true; frets[8 + g1 + str1].active = true; frets[9 + g1 + str1].active = true; frets[11 + g1 + str1].active = true; frets[13 + g1 + str1].active = true; frets[15 + g1 + str1].active = true; frets[16 + g1 + str1].active = true; frets[18 + g1 + str1].active = true; frets[20 + g1 + str1].active = true; frets[21 + g1 + str1].active = true; frets[23 + g1 + str1].active = true;
    frets[0 + g2 + str1].active = false; frets[1 + g2 + str1].active = true; frets[3 + g2 + str1].active = true; frets[4 + g2 + str1].active = true; frets[6 + g2 + str1].active = true; frets[8 + g2 + str1].active = true; frets[9 + g2 + str1].active = true; frets[11 + g2 + str1].active = true; frets[13 + g2 + str1].active = true; frets[15 + g2 + str1].active = true; frets[16 + g2 + str1].active = true; frets[18 + g2 + str1].active = true; frets[20 + g2 + str1].active = true; frets[21 + g2 + str1].active = true; frets[23 + g2 + str1].active = true;
    frets[0 + g3 + str1].active = false; frets[1 + g3 + str1].active = true; frets[3 + g3 + str1].active = true; frets[4 + g3 + str1].active = true; frets[6 + g3 + str1].active = true; frets[8 + g3 + str1].active = true; frets[9 + g3 + str1].active = true; frets[11 + g3 + str1].active = true; frets[13 + g3 + str1].active = true; frets[15 + g3 + str1].active = true; frets[16 + g3 + str1].active = true; frets[18 + g3 + str1].active = true; frets[20 + g3 + str1].active = true; frets[21 + g3 + str1].active = true; frets[23 + g3 + str1].active = true;
    // string 2
    frets[0 + g1 + str2].active = false; frets[1 + g1 + str2].active = true; frets[2 + g1 + str2].active = true; frets[4 + g1 + str2].active = true; frets[6 + g1 + str2].active = true; frets[8 + g1 + str2].active = true; frets[9 + g1 + str2].active = true; frets[11 + g1 + str2].active = true; frets[13 + g1 + str2].active = true; frets[14 + g1 + str2].active = true; frets[16 + g1 + str2].active = true; frets[18 + g1 + str2].active = true; frets[20 + g1 + str2].active = true; frets[21 + g1 + str2].active = true; frets[23 + g1 + str2].active = true;
    frets[0 + g2 + str2].active = false; frets[1 + g2 + str2].active = true; frets[2 + g2 + str2].active = true; frets[4 + g2 + str2].active = true; frets[6 + g2 + str2].active = true; frets[8 + g2 + str2].active = true; frets[9 + g2 + str2].active = true; frets[11 + g2 + str2].active = true; frets[13 + g2 + str2].active = true; frets[14 + g2 + str2].active = true; frets[16 + g2 + str2].active = true; frets[18 + g2 + str2].active = true; frets[20 + g2 + str2].active = true; frets[21 + g2 + str2].active = true; frets[23 + g2 + str2].active = true;
    frets[0 + g3 + str2].active = false; frets[1 + g3 + str2].active = true; frets[2 + g3 + str2].active = true; frets[4 + g3 + str2].active = true; frets[6 + g3 + str2].active = true; frets[8 + g3 + str2].active = true; frets[9 + g3 + str2].active = true; frets[11 + g3 + str2].active = true; frets[13 + g3 + str2].active = true; frets[14 + g3 + str2].active = true; frets[16 + g3 + str2].active = true; frets[18 + g3 + str2].active = true; frets[20 + g3 + str2].active = true; frets[21 + g3 + str2].active = true; frets[23 + g3 + str2].active = true;
    // string 3
    frets[0 + g1 + str3].active = true; frets[1 + g1 + str3].active = true; frets[3 + g1 + str3].active = true; frets[5 + g1 + str3].active = true; frets[6 + g1 + str3].active = true; frets[8 + g1 + str3].active = true; frets[10 + g1 + str3].active = true; frets[12 + g1 + str3].active = true; frets[13 + g1 + str3].active = true; frets[15 + g1 + str3].active = true; frets[17 + g1 + str3].active = true; frets[18 + g1 + str3].active = true; frets[20 + g1 + str3].active = true; frets[22 + g1 + str3].active = true; frets[24 + g1 + str3].active = true;
    frets[0 + g2 + str3].active = true; frets[1 + g2 + str3].active = true; frets[3 + g2 + str3].active = true; frets[5 + g2 + str3].active = true; frets[6 + g2 + str3].active = true; frets[8 + g2 + str3].active = true; frets[10 + g2 + str3].active = true; frets[12 + g2 + str3].active = true; frets[13 + g2 + str3].active = true; frets[15 + g2 + str3].active = true; frets[17 + g2 + str3].active = true; frets[18 + g2 + str3].active = true; frets[20 + g2 + str3].active = true; frets[22 + g2 + str3].active = true; frets[24 + g2 + str3].active = true;
    frets[0 + g3 + str3].active = true; frets[1 + g3 + str3].active = true; frets[3 + g3 + str3].active = true; frets[5 + g3 + str3].active = true; frets[6 + g3 + str3].active = true; frets[8 + g3 + str3].active = true; frets[10 + g3 + str3].active = true; frets[12 + g3 + str3].active = true; frets[13 + g3 + str3].active = true; frets[15 + g3 + str3].active = true; frets[17 + g3 + str3].active = true; frets[18 + g3 + str3].active = true; frets[20 + g3 + str3].active = true; frets[22 + g3 + str3].active = true; frets[24 + g3 + str3].active = true;
    // string 4
    frets[0 + g1 + str4].active = false; frets[1 + g1 + str4].active = true; frets[3 + g1 + str4].active = true; frets[5 + g1 + str4].active = true; frets[6 + g1 + str4].active = true; frets[8 + g1 + str4].active = true; frets[10 + g1 + str4].active = true; frets[11 + g1 + str4].active = true; frets[13 + g1 + str4].active = true; frets[15 + g1 + str4].active = true; frets[17 + g1 + str4].active = true; frets[18 + g1 + str4].active = true; frets[20 + g1 + str4].active = true; frets[22 + g1 + str4].active = true; frets[23 + g1 + str4].active = true;
    frets[0 + g2 + str4].active = false; frets[1 + g2 + str4].active = true; frets[3 + g2 + str4].active = true; frets[5 + g2 + str4].active = true; frets[6 + g2 + str4].active = true; frets[8 + g2 + str4].active = true; frets[10 + g2 + str4].active = true; frets[11 + g2 + str4].active = true; frets[13 + g2 + str4].active = true; frets[15 + g2 + str4].active = true; frets[17 + g2 + str4].active = true; frets[18 + g2 + str4].active = true; frets[20 + g2 + str4].active = true; frets[22 + g2 + str4].active = true; frets[23 + g2 + str4].active = true;
    frets[0 + g3 + str4].active = false; frets[1 + g3 + str4].active = true; frets[3 + g3 + str4].active = true; frets[5 + g3 + str4].active = true; frets[6 + g3 + str4].active = true; frets[8 + g3 + str4].active = true; frets[10 + g3 + str4].active = true; frets[11 + g3 + str4].active = true; frets[13 + g3 + str4].active = true; frets[15 + g3 + str4].active = true; frets[17 + g3 + str4].active = true; frets[18 + g3 + str4].active = true; frets[20 + g3 + str4].active = true; frets[22 + g3 + str4].active = true; frets[23 + g3 + str4].active = true;
    // string 5
    frets[0 + g1 + str5].active = false; frets[1 + g1 + str5].active = true; frets[3 + g1 + str5].active = true; frets[4 + g1 + str5].active = true; frets[6 + g1 + str5].active = true; frets[8 + g1 + str5].active = true; frets[10 + g1 + str5].active = true; frets[11 + g1 + str5].active = true; frets[13 + g1 + str5].active = true; frets[15 + g1 + str5].active = true; frets[16 + g1 + str5].active = true; frets[18 + g1 + str5].active = true; frets[20 + g1 + str5].active = true; frets[22 + g1 + str5].active = true; frets[23 + g1 + str5].active = true;
    frets[0 + g2 + str5].active = false; frets[1 + g2 + str5].active = true; frets[3 + g2 + str5].active = true; frets[4 + g2 + str5].active = true; frets[6 + g2 + str5].active = true; frets[8 + g2 + str5].active = true; frets[10 + g2 + str5].active = true; frets[11 + g2 + str5].active = true; frets[13 + g2 + str5].active = true; frets[15 + g2 + str5].active = true; frets[16 + g2 + str5].active = true; frets[18 + g2 + str5].active = true; frets[20 + g2 + str5].active = true; frets[22 + g2 + str5].active = true; frets[23 + g2 + str5].active = true;
    frets[0 + g3 + str5].active = false; frets[1 + g3 + str5].active = true; frets[3 + g3 + str5].active = true; frets[4 + g3 + str5].active = true; frets[6 + g3 + str5].active = true; frets[8 + g3 + str5].active = true; frets[10 + g3 + str5].active = true; frets[11 + g3 + str5].active = true; frets[13 + g3 + str5].active = true; frets[15 + g3 + str5].active = true; frets[16 + g3 + str5].active = true; frets[18 + g3 + str5].active = true; frets[20 + g3 + str5].active = true; frets[22 + g3 + str5].active = true; frets[23 + g3 + str5].active = true;
    // string 6
    frets[0 + g1 + str6].active = false; frets[1 + g1 + str6].active = true; frets[3 + g1 + str6].active = true; frets[4 + g1 + str6].active = true; frets[6 + g1 + str6].active = true; frets[8 + g1 + str6].active = true; frets[9 + g1 + str6].active = true; frets[11 + g1 + str6].active = true; frets[13 + g1 + str6].active = true; frets[15 + g1 + str6].active = true; frets[16 + g1 + str6].active = true; frets[18 + g1 + str6].active = true; frets[20 + g1 + str6].active = true; frets[21 + g1 + str6].active = true; frets[23 + g1 + str6].active = true;
    frets[0 + g2 + str6].active = false; frets[1 + g2 + str6].active = true; frets[3 + g2 + str6].active = true; frets[4 + g2 + str6].active = true; frets[6 + g2 + str6].active = true; frets[8 + g2 + str6].active = true; frets[9 + g2 + str6].active = true; frets[11 + g2 + str6].active = true; frets[13 + g2 + str6].active = true; frets[15 + g2 + str6].active = true; frets[16 + g2 + str6].active = true; frets[18 + g2 + str6].active = true; frets[20 + g2 + str6].active = true; frets[21 + g2 + str6].active = true; frets[23 + g2 + str6].active = true;
    frets[0 + g3 + str6].active = false; frets[1 + g3 + str6].active = true; frets[3 + g3 + str6].active = true; frets[4 + g3 + str6].active = true; frets[6 + g3 + str6].active = true; frets[8 + g3 + str6].active = true; frets[9 + g3 + str6].active = true; frets[11 + g3 + str6].active = true; frets[13 + g3 + str6].active = true; frets[15 + g3 + str6].active = true; frets[16 + g3 + str6].active = true; frets[18 + g3 + str6].active = true; frets[20 + g3 + str6].active = true; frets[21 + g3 + str6].active = true; frets[23 + g3 + str6].active = true;
  },

  lydianButton: function() {
    for (i = 0; i < frets.length; i++) {
      frets[i].active = false;
    }
    // string 1
    frets[0 + g1 + str1].active = true; frets[2 + g1 + str1].active = true; frets[3 + g1 + str1].active = true; frets[5 + g1 + str1].active = true; frets[7 + g1 + str1].active = true; frets[8 + g1 + str1].active = true; frets[10 + g1 + str1].active = true; frets[12 + g1 + str1].active = true; frets[14 + g1 + str1].active = true; frets[15 + g1 + str1].active = true; frets[17 + g1 + str1].active = true; frets[19 + g1 + str1].active = true; frets[20 + g1 + str1].active = true; frets[22 + g1 + str1].active = true; frets[24 + g1 + str1].active = true;
    frets[0 + g2 + str1].active = true; frets[2 + g2 + str1].active = true; frets[3 + g2 + str1].active = true; frets[5 + g2 + str1].active = true; frets[7 + g2 + str1].active = true; frets[8 + g2 + str1].active = true; frets[10 + g2 + str1].active = true; frets[12 + g2 + str1].active = true; frets[14 + g2 + str1].active = true; frets[15 + g2 + str1].active = true; frets[17 + g2 + str1].active = true; frets[19 + g2 + str1].active = true; frets[20 + g2 + str1].active = true; frets[22 + g2 + str1].active = true; frets[24 + g2 + str1].active = true;
    frets[0 + g3 + str1].active = true; frets[2 + g3 + str1].active = true; frets[3 + g3 + str1].active = true; frets[5 + g3 + str1].active = true; frets[7 + g3 + str1].active = true; frets[8 + g3 + str1].active = true; frets[10 + g3 + str1].active = true; frets[12 + g3 + str1].active = true; frets[14 + g3 + str1].active = true; frets[15 + g3 + str1].active = true; frets[17 + g3 + str1].active = true; frets[19 + g3 + str1].active = true; frets[20 + g3 + str1].active = true; frets[22 + g3 + str1].active = true; frets[24 + g3 + str1].active = true;
    // string 2
    frets[0 + g1 + str2].active = true; frets[1 + g1 + str2].active = true; frets[3 + g1 + str2].active = true; frets[5 + g1 + str2].active = true; frets[7 + g1 + str2].active = true; frets[8 + g1 + str2].active = true; frets[10 + g1 + str2].active = true; frets[12 + g1 + str2].active = true; frets[13 + g1 + str2].active = true; frets[15 + g1 + str2].active = true; frets[17 + g1 + str2].active = true; frets[19 + g1 + str2].active = true; frets[20 + g1 + str2].active = true; frets[22 + g1 + str2].active = true; frets[24 + g1 + str2].active = true;
    frets[0 + g2 + str2].active = true; frets[1 + g2 + str2].active = true; frets[3 + g2 + str2].active = true; frets[5 + g2 + str2].active = true; frets[7 + g2 + str2].active = true; frets[8 + g2 + str2].active = true; frets[10 + g2 + str2].active = true; frets[12 + g2 + str2].active = true; frets[13 + g2 + str2].active = true; frets[15 + g2 + str2].active = true; frets[17 + g2 + str2].active = true; frets[19 + g2 + str2].active = true; frets[20 + g2 + str2].active = true; frets[22 + g2 + str2].active = true; frets[24 + g2 + str2].active = true;
    frets[0 + g3 + str2].active = true; frets[1 + g3 + str2].active = true; frets[3 + g3 + str2].active = true; frets[5 + g3 + str2].active = true; frets[7 + g3 + str2].active = true; frets[8 + g3 + str2].active = true; frets[10 + g3 + str2].active = true; frets[12 + g3 + str2].active = true; frets[13 + g3 + str2].active = true; frets[15 + g3 + str2].active = true; frets[17 + g3 + str2].active = true; frets[19 + g3 + str2].active = true; frets[20 + g3 + str2].active = true; frets[22 + g3 + str2].active = true; frets[24 + g3 + str2].active = true;
    // string 3
    frets[0 + g1 + str3].active = true; frets[2 + g1 + str3].active = true; frets[4 + g1 + str3].active = true; frets[5 + g1 + str3].active = true; frets[7 + g1 + str3].active = true; frets[9 + g1 + str3].active = true; frets[11 + g1 + str3].active = true; frets[12 + g1 + str3].active = true; frets[14 + g1 + str3].active = true; frets[16 + g1 + str3].active = true; frets[17 + g1 + str3].active = true; frets[19 + g1 + str3].active = true; frets[21 + g1 + str3].active = true; frets[23 + g1 + str3].active = true; frets[24 + g1 + str3].active = true;
    frets[0 + g2 + str3].active = true; frets[2 + g2 + str3].active = true; frets[4 + g2 + str3].active = true; frets[5 + g2 + str3].active = true; frets[7 + g2 + str3].active = true; frets[9 + g2 + str3].active = true; frets[11 + g2 + str3].active = true; frets[12 + g2 + str3].active = true; frets[14 + g2 + str3].active = true; frets[16 + g2 + str3].active = true; frets[17 + g2 + str3].active = true; frets[19 + g2 + str3].active = true; frets[21 + g2 + str3].active = true; frets[23 + g2 + str3].active = true; frets[24 + g2 + str3].active = true;
    frets[0 + g3 + str3].active = true; frets[2 + g3 + str3].active = true; frets[4 + g3 + str3].active = true; frets[5 + g3 + str3].active = true; frets[7 + g3 + str3].active = true; frets[9 + g3 + str3].active = true; frets[11 + g3 + str3].active = true; frets[12 + g3 + str3].active = true; frets[14 + g3 + str3].active = true; frets[16 + g3 + str3].active = true; frets[17 + g3 + str3].active = true; frets[19 + g3 + str3].active = true; frets[21 + g3 + str3].active = true; frets[23 + g3 + str3].active = true; frets[24 + g3 + str3].active = true;
    // string 4
    frets[0 + g1 + str4].active = true; frets[2 + g1 + str4].active = true; frets[4 + g1 + str4].active = true; frets[5 + g1 + str4].active = true; frets[7 + g1 + str4].active = true; frets[9 + g1 + str4].active = true; frets[10 + g1 + str4].active = true; frets[12 + g1 + str4].active = true; frets[14 + g1 + str4].active = true; frets[16 + g1 + str4].active = true; frets[17 + g1 + str4].active = true; frets[19 + g1 + str4].active = true; frets[21 + g1 + str4].active = true; frets[22 + g1 + str4].active = true; frets[24 + g1 + str4].active = true;
    frets[0 + g2 + str4].active = true; frets[2 + g2 + str4].active = true; frets[4 + g2 + str4].active = true; frets[5 + g2 + str4].active = true; frets[7 + g2 + str4].active = true; frets[9 + g2 + str4].active = true; frets[10 + g2 + str4].active = true; frets[12 + g2 + str4].active = true; frets[14 + g2 + str4].active = true; frets[16 + g2 + str4].active = true; frets[17 + g2 + str4].active = true; frets[19 + g2 + str4].active = true; frets[21 + g2 + str4].active = true; frets[22 + g2 + str4].active = true; frets[24 + g2 + str4].active = true;
    frets[0 + g3 + str4].active = true; frets[2 + g3 + str4].active = true; frets[4 + g3 + str4].active = true; frets[5 + g3 + str4].active = true; frets[7 + g3 + str4].active = true; frets[9 + g3 + str4].active = true; frets[10 + g3 + str4].active = true; frets[12 + g3 + str4].active = true; frets[14 + g3 + str4].active = true; frets[16 + g3 + str4].active = true; frets[17 + g3 + str4].active = true; frets[19 + g3 + str4].active = true; frets[21 + g3 + str4].active = true; frets[22 + g3 + str4].active = true; frets[24 + g3 + str4].active = true;
    // string 5
    frets[0 + g1 + str5].active = true; frets[2 + g1 + str5].active = true; frets[3 + g1 + str5].active = true; frets[5 + g1 + str5].active = true; frets[7 + g1 + str5].active = true; frets[9 + g1 + str5].active = true; frets[10 + g1 + str5].active = true; frets[12 + g1 + str5].active = true; frets[14 + g1 + str5].active = true; frets[15 + g1 + str5].active = true; frets[17 + g1 + str5].active = true; frets[19 + g1 + str5].active = true; frets[21 + g1 + str5].active = true; frets[22 + g1 + str5].active = true; frets[24 + g1 + str5].active = true;
    frets[0 + g2 + str5].active = true; frets[2 + g2 + str5].active = true; frets[3 + g2 + str5].active = true; frets[5 + g2 + str5].active = true; frets[7 + g2 + str5].active = true; frets[9 + g2 + str5].active = true; frets[10 + g2 + str5].active = true; frets[12 + g2 + str5].active = true; frets[14 + g2 + str5].active = true; frets[15 + g2 + str5].active = true; frets[17 + g2 + str5].active = true; frets[19 + g2 + str5].active = true; frets[21 + g2 + str5].active = true; frets[22 + g2 + str5].active = true; frets[24 + g2 + str5].active = true;
    frets[0 + g3 + str5].active = true; frets[2 + g3 + str5].active = true; frets[3 + g3 + str5].active = true; frets[5 + g3 + str5].active = true; frets[7 + g3 + str5].active = true; frets[9 + g3 + str5].active = true; frets[10 + g3 + str5].active = true; frets[12 + g3 + str5].active = true; frets[14 + g3 + str5].active = true; frets[15 + g3 + str5].active = true; frets[17 + g3 + str5].active = true; frets[19 + g3 + str5].active = true; frets[21 + g3 + str5].active = true; frets[22 + g3 + str5].active = true; frets[24 + g3 + str5].active = true;
    // string 6
    frets[0 + g1 + str6].active = true; frets[2 + g1 + str6].active = true; frets[3 + g1 + str6].active = true; frets[5 + g1 + str6].active = true; frets[7 + g1 + str6].active = true; frets[8 + g1 + str6].active = true; frets[10 + g1 + str6].active = true; frets[12 + g1 + str6].active = true; frets[14 + g1 + str6].active = true; frets[15 + g1 + str6].active = true; frets[17 + g1 + str6].active = true; frets[19 + g1 + str6].active = true; frets[20 + g1 + str6].active = true; frets[22 + g1 + str6].active = true; frets[24 + g1 + str6].active = true;
    frets[0 + g2 + str6].active = true; frets[2 + g2 + str6].active = true; frets[3 + g2 + str6].active = true; frets[5 + g2 + str6].active = true; frets[7 + g2 + str6].active = true; frets[8 + g2 + str6].active = true; frets[10 + g2 + str6].active = true; frets[12 + g2 + str6].active = true; frets[14 + g2 + str6].active = true; frets[15 + g2 + str6].active = true; frets[17 + g2 + str6].active = true; frets[19 + g2 + str6].active = true; frets[20 + g2 + str6].active = true; frets[22 + g2 + str6].active = true; frets[24 + g2 + str6].active = true;
    frets[0 + g3 + str6].active = true; frets[2 + g3 + str6].active = true; frets[3 + g3 + str6].active = true; frets[5 + g3 + str6].active = true; frets[7 + g3 + str6].active = true; frets[8 + g3 + str6].active = true; frets[10 + g3 + str6].active = true; frets[12 + g3 + str6].active = true; frets[14 + g3 + str6].active = true; frets[15 + g3 + str6].active = true; frets[17 + g3 + str6].active = true; frets[19 + g3 + str6].active = true; frets[20 + g3 + str6].active = true; frets[22 + g3 + str6].active = true; frets[24 + g3 + str6].active = true;
  },

  mixoButton: function() {
    for (i = 0; i < frets.length; i++) {
      frets[i].active = false;
    }
    // string 1
    frets[0 + g1 + str1].active = true; frets[1 + g1 + str1].active = true; frets[3 + g1 + str1].active = true; frets[5 + g1 + str1].active = true; frets[6 + g1 + str1].active = true; frets[8 + g1 + str1].active = true; frets[10 + g1 + str1].active = true; frets[12 + g1 + str1].active = true; frets[13 + g1 + str1].active = true; frets[15 + g1 + str1].active = true; frets[17 + g1 + str1].active = true; frets[18 + g1 + str1].active = true; frets[20 + g1 + str1].active = true; frets[22 + g1 + str1].active = true; frets[24 + g1 + str1].active = true;
    frets[0 + g2 + str1].active = true; frets[1 + g2 + str1].active = true; frets[3 + g2 + str1].active = true; frets[5 + g2 + str1].active = true; frets[6 + g2 + str1].active = true; frets[8 + g2 + str1].active = true; frets[10 + g2 + str1].active = true; frets[12 + g2 + str1].active = true; frets[13 + g2 + str1].active = true; frets[15 + g2 + str1].active = true; frets[17 + g2 + str1].active = true; frets[18 + g2 + str1].active = true; frets[20 + g2 + str1].active = true; frets[22 + g2 + str1].active = true; frets[24 + g2 + str1].active = true;
    frets[0 + g3 + str1].active = true; frets[1 + g3 + str1].active = true; frets[3 + g3 + str1].active = true; frets[5 + g3 + str1].active = true; frets[6 + g3 + str1].active = true; frets[8 + g3 + str1].active = true; frets[10 + g3 + str1].active = true; frets[12 + g3 + str1].active = true; frets[13 + g3 + str1].active = true; frets[15 + g3 + str1].active = true; frets[17 + g3 + str1].active = true; frets[18 + g3 + str1].active = true; frets[20 + g3 + str1].active = true; frets[22 + g3 + str1].active = true; frets[24 + g3 + str1].active = true;
    // string 2
    frets[0 + g1 + str2].active = true; frets[1 + g1 + str2].active = true; frets[3 + g1 + str2].active = true; frets[5 + g1 + str2].active = true; frets[6 + g1 + str2].active = true; frets[8 + g1 + str2].active = true; frets[10 + g1 + str2].active = true; frets[11 + g1 + str2].active = true; frets[13 + g1 + str2].active = true; frets[15 + g1 + str2].active = true; frets[17 + g1 + str2].active = true; frets[18 + g1 + str2].active = true; frets[20 + g1 + str2].active = true; frets[22 + g1 + str2].active = true; frets[23 + g1 + str2].active = true;
    frets[0 + g2 + str2].active = true; frets[1 + g2 + str2].active = true; frets[3 + g2 + str2].active = true; frets[5 + g2 + str2].active = true; frets[6 + g2 + str2].active = true; frets[8 + g2 + str2].active = true; frets[10 + g2 + str2].active = true; frets[11 + g2 + str2].active = true; frets[13 + g2 + str2].active = true; frets[15 + g2 + str2].active = true; frets[17 + g2 + str2].active = true; frets[18 + g2 + str2].active = true; frets[20 + g2 + str2].active = true; frets[22 + g2 + str2].active = true; frets[23 + g2 + str2].active = true;
    frets[0 + g3 + str2].active = true; frets[1 + g3 + str2].active = true; frets[3 + g3 + str2].active = true; frets[5 + g3 + str2].active = true; frets[6 + g3 + str2].active = true; frets[8 + g3 + str2].active = true; frets[10 + g3 + str2].active = true; frets[11 + g3 + str2].active = true; frets[13 + g3 + str2].active = true; frets[15 + g3 + str2].active = true; frets[17 + g3 + str2].active = true; frets[18 + g3 + str2].active = true; frets[20 + g3 + str2].active = true; frets[22 + g3 + str2].active = true; frets[23 + g3 + str2].active = true;
    // string 3
    frets[0 + g1 + str3].active = true; frets[2 + g1 + str3].active = true; frets[3 + g1 + str3].active = true; frets[5 + g1 + str3].active = true; frets[7 + g1 + str3].active = true; frets[9 + g1 + str3].active = true; frets[10 + g1 + str3].active = true; frets[12 + g1 + str3].active = true; frets[14 + g1 + str3].active = true; frets[15 + g1 + str3].active = true; frets[17 + g1 + str3].active = true; frets[19 + g1 + str3].active = true; frets[21 + g1 + str3].active = true; frets[22 + g1 + str3].active = true; frets[24 + g1 + str3].active = true;
    frets[0 + g2 + str3].active = true; frets[2 + g2 + str3].active = true; frets[3 + g2 + str3].active = true; frets[5 + g2 + str3].active = true; frets[7 + g2 + str3].active = true; frets[9 + g2 + str3].active = true; frets[10 + g2 + str3].active = true; frets[12 + g2 + str3].active = true; frets[14 + g2 + str3].active = true; frets[15 + g2 + str3].active = true; frets[17 + g2 + str3].active = true; frets[19 + g2 + str3].active = true; frets[21 + g2 + str3].active = true; frets[22 + g2 + str3].active = true; frets[24 + g2 + str3].active = true;
    frets[0 + g3 + str3].active = true; frets[2 + g3 + str3].active = true; frets[3 + g3 + str3].active = true; frets[5 + g3 + str3].active = true; frets[7 + g3 + str3].active = true; frets[9 + g3 + str3].active = true; frets[10 + g3 + str3].active = true; frets[12 + g3 + str3].active = true; frets[14 + g3 + str3].active = true; frets[15 + g3 + str3].active = true; frets[17 + g3 + str3].active = true; frets[19 + g3 + str3].active = true; frets[21 + g3 + str3].active = true; frets[22 + g3 + str3].active = true; frets[24 + g3 + str3].active = true;
    // string 4
    frets[0 + g1 + str4].active = true; frets[2 + g1 + str4].active = true; frets[3 + g1 + str4].active = true; frets[5 + g1 + str4].active = true; frets[7 + g1 + str4].active = true; frets[8 + g1 + str4].active = true; frets[10 + g1 + str4].active = true; frets[12 + g1 + str4].active = true; frets[14 + g1 + str4].active = true; frets[15 + g1 + str4].active = true; frets[17 + g1 + str4].active = true; frets[19 + g1 + str4].active = true; frets[20 + g1 + str4].active = true; frets[22 + g1 + str4].active = true; frets[24 + g1 + str4].active = true;
    frets[0 + g2 + str4].active = true; frets[2 + g2 + str4].active = true; frets[3 + g2 + str4].active = true; frets[5 + g2 + str4].active = true; frets[7 + g2 + str4].active = true; frets[8 + g2 + str4].active = true; frets[10 + g2 + str4].active = true; frets[12 + g2 + str4].active = true; frets[14 + g2 + str4].active = true; frets[15 + g2 + str4].active = true; frets[17 + g2 + str4].active = true; frets[19 + g2 + str4].active = true; frets[20 + g2 + str4].active = true; frets[22 + g2 + str4].active = true; frets[24 + g2 + str4].active = true;
    frets[0 + g3 + str4].active = true; frets[2 + g3 + str4].active = true; frets[3 + g3 + str4].active = true; frets[5 + g3 + str4].active = true; frets[7 + g3 + str4].active = true; frets[8 + g3 + str4].active = true; frets[10 + g3 + str4].active = true; frets[12 + g3 + str4].active = true; frets[14 + g3 + str4].active = true; frets[15 + g3 + str4].active = true; frets[17 + g3 + str4].active = true; frets[19 + g3 + str4].active = true; frets[20 + g3 + str4].active = true; frets[22 + g3 + str4].active = true; frets[24 + g3 + str4].active = true;
    // string 5
    frets[0 + g1 + str5].active = true; frets[1 + g1 + str5].active = true; frets[3 + g1 + str5].active = true; frets[5 + g1 + str5].active = true; frets[7 + g1 + str5].active = true; frets[8 + g1 + str5].active = true; frets[10 + g1 + str5].active = true; frets[12 + g1 + str5].active = true; frets[13 + g1 + str5].active = true; frets[15 + g1 + str5].active = true; frets[17 + g1 + str5].active = true; frets[19 + g1 + str5].active = true; frets[20 + g1 + str5].active = true; frets[22 + g1 + str5].active = true; frets[24 + g1 + str5].active = true;
    frets[0 + g2 + str5].active = true; frets[1 + g2 + str5].active = true; frets[3 + g2 + str5].active = true; frets[5 + g2 + str5].active = true; frets[7 + g2 + str5].active = true; frets[8 + g2 + str5].active = true; frets[10 + g2 + str5].active = true; frets[12 + g2 + str5].active = true; frets[13 + g2 + str5].active = true; frets[15 + g2 + str5].active = true; frets[17 + g2 + str5].active = true; frets[19 + g2 + str5].active = true; frets[20 + g2 + str5].active = true; frets[22 + g2 + str5].active = true; frets[24 + g2 + str5].active = true;
    frets[0 + g3 + str5].active = true; frets[1 + g3 + str5].active = true; frets[3 + g3 + str5].active = true; frets[5 + g3 + str5].active = true; frets[7 + g3 + str5].active = true; frets[8 + g3 + str5].active = true; frets[10 + g3 + str5].active = true; frets[12 + g3 + str5].active = true; frets[13 + g3 + str5].active = true; frets[15 + g3 + str5].active = true; frets[17 + g3 + str5].active = true; frets[19 + g3 + str5].active = true; frets[20 + g3 + str5].active = true; frets[22 + g3 + str5].active = true; frets[24 + g3 + str5].active = true;
    // string 6
    frets[0 + g1 + str6].active = true; frets[1 + g1 + str6].active = true; frets[3 + g1 + str6].active = true; frets[5 + g1 + str6].active = true; frets[6 + g1 + str6].active = true; frets[8 + g1 + str6].active = true; frets[10 + g1 + str6].active = true; frets[12 + g1 + str6].active = true; frets[13 + g1 + str6].active = true; frets[15 + g1 + str6].active = true; frets[17 + g1 + str6].active = true; frets[18 + g1 + str6].active = true; frets[20 + g1 + str6].active = true; frets[22 + g1 + str6].active = true; frets[24 + g1 + str6].active = true;
    frets[0 + g2 + str6].active = true; frets[1 + g2 + str6].active = true; frets[3 + g2 + str6].active = true; frets[5 + g2 + str6].active = true; frets[6 + g2 + str6].active = true; frets[8 + g2 + str6].active = true; frets[10 + g2 + str6].active = true; frets[12 + g2 + str6].active = true; frets[13 + g2 + str6].active = true; frets[15 + g2 + str6].active = true; frets[17 + g2 + str6].active = true; frets[18 + g2 + str6].active = true; frets[20 + g2 + str6].active = true; frets[22 + g2 + str6].active = true; frets[24 + g2 + str6].active = true;
    frets[0 + g3 + str6].active = true; frets[1 + g3 + str6].active = true; frets[3 + g3 + str6].active = true; frets[5 + g3 + str6].active = true; frets[6 + g3 + str6].active = true; frets[8 + g3 + str6].active = true; frets[10 + g3 + str6].active = true; frets[12 + g3 + str6].active = true; frets[13 + g3 + str6].active = true; frets[15 + g3 + str6].active = true; frets[17 + g3 + str6].active = true; frets[18 + g3 + str6].active = true; frets[20 + g3 + str6].active = true; frets[22 + g3 + str6].active = true; frets[24 + g3 + str6].active = true;
  },

  aeolienButton: function() {
    for (i = 0; i < frets.length; i++) {
      frets[i].active = false;
    }
    // string 1
    frets[0 + g1 + str1].active = false; frets[1 + g1 + str1].active = true; frets[3 + g1 + str1].active = true; frets[4 + g1 + str1].active = true; frets[6 + g1 + str1].active = true; frets[8 + g1 + str1].active = true; frets[10 + g1 + str1].active = true; frets[11 + g1 + str1].active = true; frets[13 + g1 + str1].active = true; frets[15 + g1 + str1].active = true; frets[16 + g1 + str1].active = true; frets[18 + g1 + str1].active = true; frets[20 + g1 + str1].active = true; frets[22 + g1 + str1].active = true; frets[23 + g1 + str1].active = true;
    frets[0 + g2 + str1].active = false; frets[1 + g2 + str1].active = true; frets[3 + g2 + str1].active = true; frets[4 + g2 + str1].active = true; frets[6 + g2 + str1].active = true; frets[8 + g2 + str1].active = true; frets[10 + g2 + str1].active = true; frets[11 + g2 + str1].active = true; frets[13 + g2 + str1].active = true; frets[15 + g2 + str1].active = true; frets[16 + g2 + str1].active = true; frets[18 + g2 + str1].active = true; frets[20 + g2 + str1].active = true; frets[22 + g2 + str1].active = true; frets[23 + g2 + str1].active = true;
    frets[0 + g3 + str1].active = false; frets[1 + g3 + str1].active = true; frets[3 + g3 + str1].active = true; frets[4 + g3 + str1].active = true; frets[6 + g3 + str1].active = true; frets[8 + g3 + str1].active = true; frets[10 + g3 + str1].active = true; frets[11 + g3 + str1].active = true; frets[13 + g3 + str1].active = true; frets[15 + g3 + str1].active = true; frets[16 + g3 + str1].active = true; frets[18 + g3 + str1].active = true; frets[20 + g3 + str1].active = true; frets[22 + g3 + str1].active = true; frets[23 + g3 + str1].active = true;
    // string 2
    frets[0 + g1 + str2].active = false; frets[1 + g1 + str2].active = true; frets[3 + g1 + str2].active = true; frets[4 + g1 + str2].active = true; frets[6 + g1 + str2].active = true; frets[8 + g1 + str2].active = true; frets[9 + g1 + str2].active = true; frets[11 + g1 + str2].active = true; frets[13 + g1 + str2].active = true; frets[15 + g1 + str2].active = true; frets[16 + g1 + str2].active = true; frets[18 + g1 + str2].active = true; frets[20 + g1 + str2].active = true; frets[21 + g1 + str2].active = true; frets[23 + g1 + str2].active = true;
    frets[0 + g2 + str2].active = false; frets[1 + g2 + str2].active = true; frets[3 + g2 + str2].active = true; frets[4 + g2 + str2].active = true; frets[6 + g2 + str2].active = true; frets[8 + g2 + str2].active = true; frets[9 + g2 + str2].active = true; frets[11 + g2 + str2].active = true; frets[13 + g2 + str2].active = true; frets[15 + g2 + str2].active = true; frets[16 + g2 + str2].active = true; frets[18 + g2 + str2].active = true; frets[20 + g2 + str2].active = true; frets[21 + g2 + str2].active = true; frets[23 + g2 + str2].active = true;
    frets[0 + g3 + str2].active = false; frets[1 + g3 + str2].active = true; frets[3 + g3 + str2].active = true; frets[4 + g3 + str2].active = true; frets[6 + g3 + str2].active = true; frets[8 + g3 + str2].active = true; frets[9 + g3 + str2].active = true; frets[11 + g3 + str2].active = true; frets[13 + g3 + str2].active = true; frets[15 + g3 + str2].active = true; frets[16 + g3 + str2].active = true; frets[18 + g3 + str2].active = true; frets[20 + g3 + str2].active = true; frets[21 + g3 + str2].active = true; frets[23 + g3 + str2].active = true;
    // string 3
    frets[0 + g1 + str3].active = true; frets[1 + g1 + str3].active = true; frets[3 + g1 + str3].active = true; frets[5 + g1 + str3].active = true; frets[7 + g1 + str3].active = true; frets[8 + g1 + str3].active = true; frets[10 + g1 + str3].active = true; frets[12 + g1 + str3].active = true; frets[13 + g1 + str3].active = true; frets[15 + g1 + str3].active = true; frets[17 + g1 + str3].active = true; frets[19 + g1 + str3].active = true; frets[20 + g1 + str3].active = true; frets[22 + g1 + str3].active = true; frets[24 + g1 + str3].active = true;
    frets[0 + g2 + str3].active = true; frets[1 + g2 + str3].active = true; frets[3 + g2 + str3].active = true; frets[5 + g2 + str3].active = true; frets[7 + g2 + str3].active = true; frets[8 + g2 + str3].active = true; frets[10 + g2 + str3].active = true; frets[12 + g2 + str3].active = true; frets[13 + g2 + str3].active = true; frets[15 + g2 + str3].active = true; frets[17 + g2 + str3].active = true; frets[19 + g2 + str3].active = true; frets[20 + g2 + str3].active = true; frets[22 + g2 + str3].active = true; frets[24 + g2 + str3].active = true;
    frets[0 + g3 + str3].active = true; frets[1 + g3 + str3].active = true; frets[3 + g3 + str3].active = true; frets[5 + g3 + str3].active = true; frets[7 + g3 + str3].active = true; frets[8 + g3 + str3].active = true; frets[10 + g3 + str3].active = true; frets[12 + g3 + str3].active = true; frets[13 + g3 + str3].active = true; frets[15 + g3 + str3].active = true; frets[17 + g3 + str3].active = true; frets[19 + g3 + str3].active = true; frets[20 + g3 + str3].active = true; frets[22 + g3 + str3].active = true; frets[24 + g3 + str3].active = true;
    // string 4
    frets[0 + g1 + str4].active = true; frets[1 + g1 + str4].active = true; frets[3 + g1 + str4].active = true; frets[5 + g1 + str4].active = true; frets[6 + g1 + str4].active = true; frets[8 + g1 + str4].active = true; frets[10 + g1 + str4].active = true; frets[12 + g1 + str4].active = true; frets[13 + g1 + str4].active = true; frets[15 + g1 + str4].active = true; frets[17 + g1 + str4].active = true; frets[18 + g1 + str4].active = true; frets[20 + g1 + str4].active = true; frets[22 + g1 + str4].active = true; frets[24 + g1 + str4].active = true;
    frets[0 + g2 + str4].active = true; frets[1 + g2 + str4].active = true; frets[3 + g2 + str4].active = true; frets[5 + g2 + str4].active = true; frets[6 + g2 + str4].active = true; frets[8 + g2 + str4].active = true; frets[10 + g2 + str4].active = true; frets[12 + g2 + str4].active = true; frets[13 + g2 + str4].active = true; frets[15 + g2 + str4].active = true; frets[17 + g2 + str4].active = true; frets[18 + g2 + str4].active = true; frets[20 + g2 + str4].active = true; frets[22 + g2 + str4].active = true; frets[24 + g2 + str4].active = true;
    frets[0 + g3 + str4].active = true; frets[1 + g3 + str4].active = true; frets[3 + g3 + str4].active = true; frets[5 + g3 + str4].active = true; frets[6 + g3 + str4].active = true; frets[8 + g3 + str4].active = true; frets[10 + g3 + str4].active = true; frets[12 + g3 + str4].active = true; frets[13 + g3 + str4].active = true; frets[15 + g3 + str4].active = true; frets[17 + g3 + str4].active = true; frets[18 + g3 + str4].active = true; frets[20 + g3 + str4].active = true; frets[22 + g3 + str4].active = true; frets[24 + g3 + str4].active = true;
    // string 5
    frets[0 + g1 + str5].active = false; frets[1 + g1 + str5].active = true; frets[3 + g1 + str5].active = true; frets[5 + g1 + str5].active = true; frets[6 + g1 + str5].active = true; frets[8 + g1 + str5].active = true; frets[10 + g1 + str5].active = true; frets[11 + g1 + str5].active = true; frets[13 + g1 + str5].active = true; frets[15 + g1 + str5].active = true; frets[17 + g1 + str5].active = true; frets[18 + g1 + str5].active = true; frets[20 + g1 + str5].active = true; frets[22 + g1 + str5].active = true; frets[23 + g1 + str5].active = true;
    frets[0 + g2 + str5].active = false; frets[1 + g2 + str5].active = true; frets[3 + g2 + str5].active = true; frets[5 + g2 + str5].active = true; frets[6 + g2 + str5].active = true; frets[8 + g2 + str5].active = true; frets[10 + g2 + str5].active = true; frets[11 + g2 + str5].active = true; frets[13 + g2 + str5].active = true; frets[15 + g2 + str5].active = true; frets[17 + g2 + str5].active = true; frets[18 + g2 + str5].active = true; frets[20 + g2 + str5].active = true; frets[22 + g2 + str5].active = true; frets[23 + g2 + str5].active = true;
    frets[0 + g3 + str5].active = false; frets[1 + g3 + str5].active = true; frets[3 + g3 + str5].active = true; frets[5 + g3 + str5].active = true; frets[6 + g3 + str5].active = true; frets[8 + g3 + str5].active = true; frets[10 + g3 + str5].active = true; frets[11 + g3 + str5].active = true; frets[13 + g3 + str5].active = true; frets[15 + g3 + str5].active = true; frets[17 + g3 + str5].active = true; frets[18 + g3 + str5].active = true; frets[20 + g3 + str5].active = true; frets[22 + g3 + str5].active = true; frets[23 + g3 + str5].active = true;
    // string 6
    frets[0 + g1 + str6].active = false; frets[1 + g1 + str6].active = true; frets[3 + g1 + str6].active = true; frets[4 + g1 + str6].active = true; frets[6 + g1 + str6].active = true; frets[8 + g1 + str6].active = true; frets[10 + g1 + str6].active = true; frets[11 + g1 + str6].active = true; frets[13 + g1 + str6].active = true; frets[15 + g1 + str6].active = true; frets[16 + g1 + str6].active = true; frets[18 + g1 + str6].active = true; frets[20 + g1 + str6].active = true; frets[22 + g1 + str6].active = true; frets[23 + g1 + str6].active = true;
    frets[0 + g2 + str6].active = false; frets[1 + g2 + str6].active = true; frets[3 + g2 + str6].active = true; frets[4 + g2 + str6].active = true; frets[6 + g2 + str6].active = true; frets[8 + g2 + str6].active = true; frets[10 + g2 + str6].active = true; frets[11 + g2 + str6].active = true; frets[13 + g2 + str6].active = true; frets[15 + g2 + str6].active = true; frets[16 + g2 + str6].active = true; frets[18 + g2 + str6].active = true; frets[20 + g2 + str6].active = true; frets[22 + g2 + str6].active = true; frets[23 + g2 + str6].active = true;
    frets[0 + g3 + str6].active = false; frets[1 + g3 + str6].active = true; frets[3 + g3 + str6].active = true; frets[4 + g3 + str6].active = true; frets[6 + g3 + str6].active = true; frets[8 + g3 + str6].active = true; frets[10 + g3 + str6].active = true; frets[11 + g3 + str6].active = true; frets[13 + g3 + str6].active = true; frets[15 + g3 + str6].active = true; frets[16 + g3 + str6].active = true; frets[18 + g3 + str6].active = true; frets[20 + g3 + str6].active = true; frets[22 + g3 + str6].active = true; frets[23 + g3 + str6].active = true;
  },

  locrianButton: function() {
    for (i = 0; i < frets.length; i++) {
      frets[i].active = false;
    }
    // string 1
    frets[0 + g1 + str1].active = false; frets[1 + g1 + str1].active = true; frets[2 + g1 + str1].active = true; frets[4 + g1 + str1].active = true; frets[6 + g1 + str1].active = true; frets[8 + g1 + str1].active = true; frets[9 + g1 + str1].active = true; frets[11 + g1 + str1].active = true; frets[13 + g1 + str1].active = true; frets[14 + g1 + str1].active = true; frets[16 + g1 + str1].active = true; frets[18 + g1 + str1].active = true; frets[20 + g1 + str1].active = true; frets[21 + g1 + str1].active = true; frets[23 + g1 + str1].active = true;
    frets[0 + g2 + str1].active = false; frets[1 + g2 + str1].active = true; frets[2 + g2 + str1].active = true; frets[4 + g2 + str1].active = true; frets[6 + g2 + str1].active = true; frets[8 + g2 + str1].active = true; frets[9 + g2 + str1].active = true; frets[11 + g2 + str1].active = true; frets[13 + g2 + str1].active = true; frets[14 + g2 + str1].active = true; frets[16 + g2 + str1].active = true; frets[18 + g2 + str1].active = true; frets[20 + g2 + str1].active = true; frets[21 + g2 + str1].active = true; frets[23 + g2 + str1].active = true;
    frets[0 + g3 + str1].active = false; frets[1 + g3 + str1].active = true; frets[2 + g3 + str1].active = true; frets[4 + g3 + str1].active = true; frets[6 + g3 + str1].active = true; frets[8 + g3 + str1].active = true; frets[9 + g3 + str1].active = true; frets[11 + g3 + str1].active = true; frets[13 + g3 + str1].active = true; frets[14 + g3 + str1].active = true; frets[16 + g3 + str1].active = true; frets[18 + g3 + str1].active = true; frets[20 + g3 + str1].active = true; frets[21 + g3 + str1].active = true; frets[23 + g3 + str1].active = true;
    // string 2
    frets[0 + g1 + str2].active = false; frets[1 + g1 + str2].active = true; frets[2 + g1 + str2].active = true; frets[4 + g1 + str2].active = true; frets[6 + g1 + str2].active = true; frets[7 + g1 + str2].active = true; frets[9 + g1 + str2].active = true; frets[11 + g1 + str2].active = true; frets[13 + g1 + str2].active = true; frets[14 + g1 + str2].active = true; frets[16 + g1 + str2].active = true; frets[18 + g1 + str2].active = true; frets[19 + g1 + str2].active = true; frets[21 + g1 + str2].active = true; frets[23 + g1 + str2].active = true;
    frets[0 + g2 + str2].active = false; frets[1 + g2 + str2].active = true; frets[2 + g2 + str2].active = true; frets[4 + g2 + str2].active = true; frets[6 + g2 + str2].active = true; frets[7 + g2 + str2].active = true; frets[9 + g2 + str2].active = true; frets[11 + g2 + str2].active = true; frets[13 + g2 + str2].active = true; frets[14 + g2 + str2].active = true; frets[16 + g2 + str2].active = true; frets[18 + g2 + str2].active = true; frets[19 + g2 + str2].active = true; frets[21 + g2 + str2].active = true; frets[23 + g2 + str2].active = true;
    frets[0 + g3 + str2].active = false; frets[1 + g3 + str2].active = true; frets[2 + g3 + str2].active = true; frets[4 + g3 + str2].active = true; frets[6 + g3 + str2].active = true; frets[7 + g3 + str2].active = true; frets[9 + g3 + str2].active = true; frets[11 + g3 + str2].active = true; frets[13 + g3 + str2].active = true; frets[14 + g3 + str2].active = true; frets[16 + g3 + str2].active = true; frets[18 + g3 + str2].active = true; frets[19 + g3 + str2].active = true; frets[21 + g3 + str2].active = true; frets[23 + g3 + str2].active = true;
    // string 3
    frets[0 + g1 + str3].active = false; frets[1 + g1 + str3].active = true; frets[3 + g1 + str3].active = true; frets[5 + g1 + str3].active = true; frets[6 + g1 + str3].active = true; frets[8 + g1 + str3].active = true; frets[10 + g1 + str3].active = true; frets[11 + g1 + str3].active = true; frets[13 + g1 + str3].active = true; frets[15 + g1 + str3].active = true; frets[17 + g1 + str3].active = true; frets[18 + g1 + str3].active = true; frets[20 + g1 + str3].active = true; frets[22 + g1 + str3].active = true; frets[23 + g1 + str3].active = true;
    frets[0 + g2 + str3].active = false; frets[1 + g2 + str3].active = true; frets[3 + g2 + str3].active = true; frets[5 + g2 + str3].active = true; frets[6 + g2 + str3].active = true; frets[8 + g2 + str3].active = true; frets[10 + g2 + str3].active = true; frets[11 + g2 + str3].active = true; frets[13 + g2 + str3].active = true; frets[15 + g2 + str3].active = true; frets[17 + g2 + str3].active = true; frets[18 + g2 + str3].active = true; frets[20 + g2 + str3].active = true; frets[22 + g2 + str3].active = true; frets[23 + g2 + str3].active = true;
    frets[0 + g3 + str3].active = false; frets[1 + g3 + str3].active = true; frets[3 + g3 + str3].active = true; frets[5 + g3 + str3].active = true; frets[6 + g3 + str3].active = true; frets[8 + g3 + str3].active = true; frets[10 + g3 + str3].active = true; frets[11 + g3 + str3].active = true; frets[13 + g3 + str3].active = true; frets[15 + g3 + str3].active = true; frets[17 + g3 + str3].active = true; frets[18 + g3 + str3].active = true; frets[20 + g3 + str3].active = true; frets[22 + g3 + str3].active = true; frets[23 + g3 + str3].active = true;
    // string 4
    frets[0 + g1 + str4].active = false; frets[1 + g1 + str4].active = true; frets[3 + g1 + str4].active = true; frets[4 + g1 + str4].active = true; frets[6 + g1 + str4].active = true; frets[8 + g1 + str4].active = true; frets[10 + g1 + str4].active = true; frets[11 + g1 + str4].active = true; frets[13 + g1 + str4].active = true; frets[15 + g1 + str4].active = true; frets[16 + g1 + str4].active = true; frets[18 + g1 + str4].active = true; frets[20 + g1 + str4].active = true; frets[22 + g1 + str4].active = true; frets[23 + g1 + str4].active = true;
    frets[0 + g2 + str4].active = false; frets[1 + g2 + str4].active = true; frets[3 + g2 + str4].active = true; frets[4 + g2 + str4].active = true; frets[6 + g2 + str4].active = true; frets[8 + g2 + str4].active = true; frets[10 + g2 + str4].active = true; frets[11 + g2 + str4].active = true; frets[13 + g2 + str4].active = true; frets[15 + g2 + str4].active = true; frets[16 + g2 + str4].active = true; frets[18 + g2 + str4].active = true; frets[20 + g2 + str4].active = true; frets[22 + g2 + str4].active = true; frets[23 + g2 + str4].active = true;
    frets[0 + g3 + str4].active = false; frets[1 + g3 + str4].active = true; frets[3 + g3 + str4].active = true; frets[4 + g3 + str4].active = true; frets[6 + g3 + str4].active = true; frets[8 + g3 + str4].active = true; frets[10 + g3 + str4].active = true; frets[11 + g3 + str4].active = true; frets[13 + g3 + str4].active = true; frets[15 + g3 + str4].active = true; frets[16 + g3 + str4].active = true; frets[18 + g3 + str4].active = true; frets[20 + g3 + str4].active = true; frets[22 + g3 + str4].active = true; frets[23 + g3 + str4].active = true;
    // string 5
    frets[0 + g1 + str5].active = false; frets[1 + g1 + str5].active = true; frets[3 + g1 + str5].active = true; frets[4 + g1 + str5].active = true; frets[6 + g1 + str5].active = true; frets[8 + g1 + str5].active = true; frets[9 + g1 + str5].active = true; frets[11 + g1 + str5].active = true; frets[13 + g1 + str5].active = true; frets[15 + g1 + str5].active = true; frets[16 + g1 + str5].active = true; frets[18 + g1 + str5].active = true; frets[20 + g1 + str5].active = true; frets[21 + g1 + str5].active = true; frets[23 + g1 + str5].active = true;
    frets[0 + g2 + str5].active = false; frets[1 + g2 + str5].active = true; frets[3 + g2 + str5].active = true; frets[4 + g2 + str5].active = true; frets[6 + g2 + str5].active = true; frets[8 + g2 + str5].active = true; frets[9 + g2 + str5].active = true; frets[11 + g2 + str5].active = true; frets[13 + g2 + str5].active = true; frets[15 + g2 + str5].active = true; frets[16 + g2 + str5].active = true; frets[18 + g2 + str5].active = true; frets[20 + g2 + str5].active = true; frets[21 + g2 + str5].active = true; frets[23 + g2 + str5].active = true;
    frets[0 + g3 + str5].active = false; frets[1 + g3 + str5].active = true; frets[3 + g3 + str5].active = true; frets[4 + g3 + str5].active = true; frets[6 + g3 + str5].active = true; frets[8 + g3 + str5].active = true; frets[9 + g3 + str5].active = true; frets[11 + g3 + str5].active = true; frets[13 + g3 + str5].active = true; frets[15 + g3 + str5].active = true; frets[16 + g3 + str5].active = true; frets[18 + g3 + str5].active = true; frets[20 + g3 + str5].active = true; frets[21 + g3 + str5].active = true; frets[23 + g3 + str5].active = true;
    // string 6
    frets[0 + g1 + str6].active = false; frets[1 + g1 + str6].active = true; frets[2 + g1 + str6].active = true; frets[4 + g1 + str6].active = true; frets[6 + g1 + str6].active = true; frets[8 + g1 + str6].active = true; frets[9 + g1 + str6].active = true; frets[11 + g1 + str6].active = true; frets[13 + g1 + str6].active = true; frets[14 + g1 + str6].active = true; frets[16 + g1 + str6].active = true; frets[18 + g1 + str6].active = true; frets[20 + g1 + str6].active = true; frets[21 + g1 + str6].active = true; frets[23 + g1 + str6].active = true;
    frets[0 + g2 + str6].active = false; frets[1 + g2 + str6].active = true; frets[2 + g2 + str6].active = true; frets[4 + g2 + str6].active = true; frets[6 + g2 + str6].active = true; frets[8 + g2 + str6].active = true; frets[9 + g2 + str6].active = true; frets[11 + g2 + str6].active = true; frets[13 + g2 + str6].active = true; frets[14 + g2 + str6].active = true; frets[16 + g2 + str6].active = true; frets[18 + g2 + str6].active = true; frets[20 + g2 + str6].active = true; frets[21 + g2 + str6].active = true; frets[23 + g2 + str6].active = true;
    frets[0 + g3 + str6].active = false; frets[1 + g3 + str6].active = true; frets[2 + g3 + str6].active = true; frets[4 + g3 + str6].active = true; frets[6 + g3 + str6].active = true; frets[8 + g3 + str6].active = true; frets[9 + g3 + str6].active = true; frets[11 + g3 + str6].active = true; frets[13 + g3 + str6].active = true; frets[14 + g3 + str6].active = true; frets[16 + g3 + str6].active = true; frets[18 + g3 + str6].active = true; frets[20 + g3 + str6].active = true; frets[21 + g3 + str6].active = true; frets[23 + g3 + str6].active = true;
  }
}
